services:
  app:
    build: .
    container_name: result_management_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    command: sh -c "sleep 20 && node app.js"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
