services:
  app:
    build: .
    container_name: result_management_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "sleep 20 && node app.js"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: result_management
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
